username: <e.g. centos>
key_file_path: <local_key_file_path>

manager:
  cluster_members:
  - host_ip: ''
    new_external_cert: ''
    new_external_key: ''
    new_internal_cert: ''
    new_internal_key: ''
    new_postgresql_client_cert: ''
    new_postgresql_client_key: ''
  - host_ip: ''
    new_external_cert: ''
    new_external_key: ''
    new_internal_cert: ''
    new_internal_key: ''
    new_postgresql_client_cert: ''
    new_postgresql_client_key: ''
  - host_ip: ''
    new_external_cert: ''
    new_external_key: ''
    new_internal_cert: ''
    new_internal_key: ''
    new_postgresql_client_cert: ''
    new_postgresql_client_key: ''
  new_ca_cert: ''
  new_external_ca_cert: ''
  new_ldap_ca_cert: '' # Relevant only if using ldap
postgresql_server:
  cluster_members:
  - host_ip: ''
    new_cert: ''
    new_key: ''
  - host_ip: ''
    new_cert: ''
    new_key: ''
  - host_ip: ''
    new_cert: ''
    new_key: ''
  new_ca_cert: '' # If specified, the postgresql_client certs in the managers need to be replaced as well
rabbitmq:
  cluster_members:
  - host_ip: ''
    new_cert: ''
    new_key: ''
  - host_ip: ''
    new_cert: ''
    new_key: ''
  - host_ip: ''
    new_cert: ''
    new_key: ''
  new_ca_cert: ''
