auth_url:
username:
password:
region_name:
tenant_name:
image_id: 70de1e0f-2951-4eae-9a8f-05afd97cd036 #centos-7 image_id
machine_username: centos
flavor_id: 2 #m1.small
gateway_net_id: dda079ce-12cf-4309-879a-8e67aec94de4
network_id:
key_name:
key_file_path:
using_load_balancer: true
manager_rpm_download_link: http://repository.cloudifysource.org/cloudify/5.0.5/m1-release/cloudify-manager-install-5.0.5m1.rpm
manager_rpm_name: cloudify-manager-install-5.0.5m1.rpm
cloudify_license_path:
