auth_url: ''  #from the RC file
username: '' #from the RC file
password: '' #your password for Openstack
region_name: '' #from the RC file
tenant_name: '' #from the RC file
network_name: '' #the network name you created on Openstack
key_name: '' #the name of the key you created on Openstack
key_file_path: '' #your private key local path, should match the key that you created on Openstack
cloudify_license_path: '' #local path to a valid Cloudify license
image_name: 'CentOS-7_6-x86_64-GenericCloud'
machine_username: 'centos' #for rhel use "cloud-user"
flavor_name: 'm1.small' #for rhel or for big memory consumption, use m1.medium
gateway_network_name: 'GATEWAY_NET'
using_load_balancer: true
manager_rpm_download_link: 'http://cloudify-release-eu.s3.amazonaws.com/cloudify/5.0.5/.dev1-release/cloudify-manager-install-5.0.5-.dev1.x86_64.rpm'
manager_rpm_name: 'cloudify-manager-install-5.0.5-.dev1.x86_64.rpm'
number_of_instances:
  postgresql: 3 # must be greater than or equal to 2
  rabbitmq: 3 # must be greater than or equal to 1
  manager: 3 # must be greater than or equal to 1
