manager:
  hostname: <manager host name, e.g. manager2>
  security:
    ssl_enabled: true
    admin_password: admin

rabbitmq:
  username:
  password:
  ca_path:
  cluster_members:
    <first rabbitmq instance-name>:
      default: <first rabbitmq private-ip>
    <second rabbitmq instance-name>:
      default: <second rabbitmq private-ip>
    <third rabbitmq instance-name>:
      default: <third rabbitmq private-ip>

postgresql_server:
  ssl_enabled: true
  ca_path:

  postgres_password: 'somesecretvalue123!'
  cluster:
    nodes:
      - <first db private-ip>
      - <second db private-ip>
      - <third db private-ip>

postgresql_client:
  ssl_enabled: true
  server_password: 'somesecretvalue123!'
  ssl_client_verification: true

validations:
  minimum_required_total_physical_memory_in_mb: 1024

ssl_inputs:
  ca_cert_path:
  internal_cert_path:
  internal_key_path:
  postgresql_client_cert_path:
  postgresql_client_key_path:
  external_cert_path:
  external_key_path:
  external_ca_cert_path:

services_to_install:
  - manager_service
