manager:
  private_ip:
  public_ip:
  hostname: <manager host name, e.g. manager2>
  security:
    ssl_enabled: true
    admin_password: admin
  monitoring:
    username: 'monitoringusername'
    password: 'longyeteasytorememberstringasapassword'

rabbitmq:
  ca_path:
  cluster_members:
    <first rabbitmq instance-name>:
      networks:
        default: <first rabbitmq private-ip>
    <second rabbitmq instance-name>:
      networks:
        default: <first rabbitmq private-ip>
    <third rabbitmq instance-name>:
      networks:
        default: <first rabbitmq private-ip>
  monitoring:
    username: 'monitoringusername'
    password: 'longyeteasytorememberstringasapassword'

postgresql_server:
   # When using external db, ssl_enabled will be poped.
  ssl_enabled: true
  ca_path:
  # When using external db, postgres_password will be poped.
  postgres_password: 'somesecretvalue123!'
  cluster:
    nodes:
      <first postgresql instance-name>:
        ip:
      <second postgresql instance-name>:
        ip:
      <third postgresql instance-name>:
        ip:

postgresql_client:
  ssl_enabled: true
  # When using external db, server_password will be overridden.
  server_password: 'somesecretvalue123!'
  # When using external db, ssl_client_verification will be overridden to false.
  ssl_client_verification: true
  monitoring:
    username: 'monitoringusername'
    password: 'longyeteasytorememberstringasapassword'

validations:
  minimum_required_total_physical_memory_in_mb: 1024

agent:
  networks:
    default: <load_balancer private-ip>

ssl_inputs:
  ca_cert_path:
  internal_cert_path:
  internal_key_path:
  postgresql_client_cert_path:
  postgresql_client_key_path:
  external_cert_path:
  external_key_path:
  external_ca_cert_path:


prometheus:
  credentials:
    username: 'monitoringusername'
    password: 'longyeteasytorememberstringasapassword'
  blackbox_exporter:
    ca_cert_path:

  cert_path:
  key_path:
  ca_path:

services_to_install:
  - manager_service
  - monitoring_service
