manager:
  private_ip: <current rabbitmq private-ip>
  public_ip: <current rabbitmq private-ip>

rabbitmq:
  username:
  password:

  cluster_members:
    <first rabbitmq instance-name>:
      networks:
        default: <first rabbitmq private-ip>
    <second rabbitmq instance-name>:
      networks:
        default: <second rabbitmq private-ip>
    <third rabbitmq instance-name>:
      networks:
        default: <third rabbitmq private-ip>

  cert_path:
  key_path:
  ca_path:

  nodename: '<current rabbitmq instance-name>'

  erlang_cookie: 'securesharedtoken'

prometheus:
  credentials:
    username: 'monitoringusername'
    password: 'longyeteasytorememberstringasapassword'

  cert_path:
  key_path:
  ca_path:

validations:
  minimum_required_total_physical_memory_in_mb: 1024

ssl_inputs:
  internal_cert_path:
  internal_key_path:
  ca_cert_path:

services_to_install:
  - queue_service
  - monitoring_service
